import { ExitIcon } from "@radix-ui/react-icons";
import {
  Users,
  Coffee,
  Wifi,
  Monitor,
  BookOpen,
  Bluetooth,
  AirVentIcon,
  Power,
  Speaker,
  GuitarIcon,
  Proportions,
  Dock,
  Lightbulb,
  DoorOpenIcon,
  BookAudioIcon,
  BatteryCharging,
  CoffeeIcon,
  RockingChair,
  Blinds,
  BriefcaseMedicalIcon,
  FireExtinguisher,
  Grid2X2,
  Grab,
  Cable,
  Flame,
  Flower2,
  TouchpadIcon,
  KeyRound,
  MonitorSmartphone,
  FolderLock,
  Newspaper,
  Mic,
  Wine,
  PalmtreeIcon,
  MicIcon,
  Fan,
  PrinterIcon,
  Projector as ProjectorIcon,
  Refrigerator as RefrigeratorIcon,
  Camera,
  SquareGanttChartIcon,
  Lock,
  Cigarette,
  LayoutPanelTopIcon,
  Tv,
  UsbIcon,
  Video,
  Clock,
  MonitorUp,
  Trash2,
  Droplets,
  ClipboardEdit,
  Usb,
  ScanLine,
  ThermometerSnowflakeIcon,
  Headset
} from "lucide-react";

export const facilityIcons = {
  "Acoustic Panels": <GuitarIcon className="h-4 w-4" />,
  "Adjustable Desks": <Dock className="h-4 w-4" />,
  "Adjustable Lighting": <Lightbulb className="h-4 w-4" />,
  "Automatic Door": <DoorOpenIcon className="h-4 w-4" />,
  Bookshelf: <BookAudioIcon className="h-4 w-4" />,
  "Charging Stations": <BatteryCharging className="h-4 w-4" />,
  "CO2 Detector": <AirVentIcon className="h-4 w-4" />,
  "Coffee Machine": <CoffeeIcon className="h-4 w-4" />,
  "Comfortable Chairs": <RockingChair className="h-4 w-4" />,
  "Conference Table": <Dock className="h-4 w-4" />,
  Couch: <RockingChair className="h-4 w-4" />,
  "Curtains/Blinds": <Blinds className="h-4 w-4" />,
  "Emergency Exit": <ExitIcon className="h-4 w-4" />,
  "Emergency First Aid Kit": <BriefcaseMedicalIcon className="h-4 w-4" />,
  "Fire Extinguisher": <FireExtinguisher className="h-4 w-4" />,
  "Folding Chairs": <RockingChair className="h-4 w-4" />,
  Projector: <ProjectorIcon className="h-4 w-4" />,
  Whiteboard: <BookOpen className="h-4 w-4" />,
  "Video Conference": <Users className="h-4 w-4" />,
  "Glass Walls": <Grid2X2 className="h-4 w-4" />,
  "Hand Sanitizer Station": <Grab className="h-4 w-4" />,
  "TV Screen": <Monitor className="h-4 w-4" />,
  WiFi: <Wifi className="h-4 w-4" />,
  Catering: <Coffee className="h-4 w-4" />,
  Microphone: <Mic className="h-4 w-4" />,
  "Air Conditioning": <AirVentIcon className="h-4 w-4" />,
  "Bluetooth Speakers": <Bluetooth className="h-4 w-4" />,
  "Power Outlets": <Power className="h-4 w-4" />,
  "Sound System": <Speaker className="h-4 w-4" />,
  
  // New icons for the remaining items
  "Handheld Remote Control": <Usb className="h-4 w-4" />,
  "HDMI Cables": <Cable className="h-4 w-4" />,
  "Heater": <Flame className="h-4 w-4" />,
  "Indoor Plants": <Flower2 className="h-4 w-4" />,
  "Interactive Touchscreen": <TouchpadIcon className="h-4 w-4" />,
  "Key Card Access": <KeyRound className="h-4 w-4" />,
  "LED Display Panels": <MonitorSmartphone className="h-4 w-4" />,
  "Locker Storage": <FolderLock className="h-4 w-4" />,
  "Magazine Rack": <Newspaper className="h-4 w-4" />,
  "Mini Bar": <Wine className="h-4 w-4" />,
  "Outdoor Patio": <PalmtreeIcon className="h-4 w-4" />,
  "Podium": <MicIcon className="h-4 w-4" />,
  "Portable Fan": <Fan className="h-4 w-4" />,
  "Printer": <PrinterIcon className="h-4 w-4" />,
  "Refrigerator": <RefrigeratorIcon className="h-4 w-4" />,
  "Scanner": <ScanLine className="h-4 w-4" />,
  "Security Cameras": <Camera className="h-4 w-4" />,
  "Smart Board": <SquareGanttChartIcon className="h-4 w-4" />,
  "Smart Lighting": <Lightbulb className="h-4 w-4" />,
  "Smart Lock": <Lock className="h-4 w-4" />,
  "Smart Thermostat": <ThermometerSnowflakeIcon className="h-4 w-4" />,
  "Smoke Detector": <Cigarette className="h-4 w-4" />,
  "Stage": <LayoutPanelTopIcon className="h-4 w-4" />,
  "Surround Sound Speakers": <Speaker className="h-4 w-4" />,
  "Television": <Tv className="h-4 w-4" />,
  "USB Hubs": <UsbIcon className="h-4 w-4" />,
  "Video Conferencing": <Video className="h-4 w-4" />,
  "VR Equipment": <Headset className="h-4 w-4" />,
  "Wall Clock": <Clock className="h-4 w-4" />,
  "Wall-Mounted TV": <MonitorUp className="h-4 w-4" />,
  "Waste Bins": <Trash2 className="h-4 w-4" />,
  "Water Dispenser": <Droplets className="h-4 w-4" />,
  "Wireless Charging Pads": <BatteryCharging className="h-4 w-4" />,
  "Writing Pads & Pens": <ClipboardEdit className="h-4 w-4" />,
};